{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "86832337",
   "metadata": {},
   "source": [
    "## Section1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "2055bd43",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "==================================================\n",
      "   Space Recommendation - Open Source Project\n",
      "   Project Lead : Yerim\n",
      "==================================================\n",
      "Each field by index\n",
      "Space Recommendation 1.0 2026 python Yerim\n",
      "Name : Space Recommendation  |  Version : 1.0  |  Started : 2026\n",
      "First 3 fields  : ('Space Recommendation', '1.0', 2026)\n",
      "Language count  : 1    Language index : 3\n",
      "# project[1] = 2.0 -> TypeError: 'tuple' object does not support item assignment -> Because tuple is immutable.\n",
      "--------------------------------------------------\n",
      "Sorted names    : ['Bob', 'Chloe', 'James', 'Yerim']\n",
      "Last name       : Yerim           First two : ['Bob', 'Chloe']\n",
      "Contributor 1 status : Active\n",
      "Backup : {'name': 'Yerim', 'role': 'Junior Developer', 'language': 'Python', 'commits': 10, 'country': 'Republic of Korea', 'status': 'Active'}\n"
     ]
    }
   ],
   "source": [
    "project = (\"Space Recommendation\", \"1.0\", 2026, \"python\", \"Yerim\")\n",
    "\n",
    "print(\"=\" * 50)\n",
    "print(f\"   {project[0]} - Open Source Project\")\n",
    "print(f\"   Project Lead : {project[-1]}\")\n",
    "print(\"=\" * 50)\n",
    "\n",
    "print(\"Each field by index\")\n",
    "print(project[0], project[1], project[2], project[3], project[4])\n",
    "\n",
    "print(f\"Name : {project[0]}  |  Version : {project[1]}  |  Started : {project[2]}\")\n",
    "print(f\"First 3 fields  : {project[:3]}\")\n",
    "print(f\"Language count  : {project.count('python')}    Language index : {project.index('python')}\")\n",
    "print(\"# project[1] = 2.0 -> TypeError: 'tuple' object does not support item assignment -> Because tuple is immutable.\")\n",
    "print(\"-\" * 50)\n",
    "\n",
    "contributors = []\n",
    "\n",
    "for _ in range(4):\n",
    "    name = input(\"Name: \")\n",
    "    role = input(\"Role: \")\n",
    "    language = input(\"Language: \")\n",
    "    commits = int(input(\"Commits: \"))\n",
    "    country = input(\"Country: \")\n",
    "    contributor = {\"name\" : name,\n",
    "                   \"role\" : role,\n",
    "                   \"language\" : language,\n",
    "                   \"commits\" : commits,\n",
    "                   \"country\" : country\n",
    "                   }\n",
    "    contributors.append(contributor)\n",
    "\n",
    "names = [c[\"name\"] for c in contributors]\n",
    "names.sort()\n",
    "print(f\"Sorted names    : {names}\")\n",
    "print(f\"Last name       : {names[-1]}           First two : {names[:2]}\")\n",
    "\n",
    "for c in contributors:\n",
    "    c.update({\"status\" : \"Active\"})\n",
    "print(f\"Contributor 1 status : {contributors[0].get('status')}\")\n",
    "\n",
    "cont1 = contributors[0].copy()\n",
    "print(f\"Backup : {cont1}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b304df26",
   "metadata": {},
   "source": [
    "## Section2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "d34a1ac0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Open issues  : 2\n",
      "First issue -> priority updated to Critical.\n",
      "Last two issues : [{'id': 4, 'title': '200 Success', 'type': 'Feature', 'priority': 'Low', 'reporter': 'Chloe', 'status': 'Resolved'}, {'id': 5, 'title': 'Syntax Error', 'type': 'Bug', 'priority': 'Critical', 'reporter': 'James', 'status': 'In Progress'}]\n",
      "--------------------------------------------------\n",
      "reporters   : {'James', 'Yerim', 'Chloe', 'Bob'}\n",
      "tech_stack  : {'Python', 'CSS', 'C', 'Java'}\n",
      "union       : {'Python', 'Yerim', 'CSS', 'Chloe', 'C', 'Bob', 'James', 'Java'}\n",
      "intersection: set()   difference : {'James', 'Yerim', 'Chloe', 'Bob'}\n",
      "Critical present  : Yes - flag for immediate review.\n",
      "--------------------------------------------------\n",
      "priority keys : dict_keys(['Critical', 'High', 'Medium', 'Low'])\n",
      "priority values : dict_values([2, 1, 1, 1])\n",
      "Status_Groups -> Open : ['404 Error', 'New code submitted']   |   In Progress : ['500 Error', 'Syntax Error']   |   Resolved : ['200 Success']\n",
      "Status Keys : dict_keys(['Open', 'In Progress', 'Resolved'])\n",
      "Status Values : dict_values([['404 Error', 'New code submitted'], ['500 Error', 'Syntax Error'], ['200 Success']])\n",
      "Top reporter   : James (2 issues)\n",
      "After pop('type') : {'id': 1, 'title': '404 Error', 'priority': 'Critical', 'reporter': 'James', 'status': 'Open'}\n"
     ]
    }
   ],
   "source": [
    "issues = []\n",
    "for _ in range(5):\n",
    "    id = int(input(\"Id: \"))\n",
    "    title = input(\"Title: \")\n",
    "\n",
    "    type = input(\"Type (Bug/Feature): \")\n",
    "    while type.lower() not in ['bug', 'feature']:\n",
    "        type = input(\"Invalid input. Please type 'Bug/'Feature': \")\n",
    "\n",
    "    priority = input(\"Priority (Critical/High/Medium/Low): \")\n",
    "    while priority.lower() not in ['critical', 'high', 'medium', 'low']:\n",
    "        priority = input(\"Invalid input. Please type 'Critical/High/Medium/Low': \")\n",
    "    \n",
    "    reporter = input(\"Reporter: \")\n",
    "    status = input(\"Status (Open/In Progress/Resolved): \")\n",
    "    while status.lower() not in ['open', 'in progress', 'resolved']:\n",
    "        status = input(\"Invalid input. Please type 'Open/In Progress/Resolved': \")\n",
    "    issue = {\"id\" : id,\n",
    "             \"title\" : title,\n",
    "             \"type\" : type,\n",
    "             \"priority\" : priority,\n",
    "             \"reporter\" : reporter,\n",
    "             \"status\" : status\n",
    "            }\n",
    "    issues.append(issue)\n",
    "\n",
    "open_count = 0\n",
    "for issue in issues:\n",
    "    if issue.get('status') == 'Open':\n",
    "        open_count += 1\n",
    "print(f\"Open issues  : {open_count}\")\n",
    "issues[0][\"priority\"] = \"Critical\"\n",
    "print(\"First issue -> priority updated to Critical.\")\n",
    "print(f\"Last two issues : {issues[-2:]}\")\n",
    "\n",
    "\n",
    "print(\"-\" * 50)\n",
    "reporters = set()\n",
    "for issue in issues:\n",
    "    reporters.add(issue['reporter'])\n",
    "print(f\"reporters   : {reporters}\")\n",
    "\n",
    "tech_stack = set()\n",
    "for c in contributors:\n",
    "    tech_stack.add(c['language'])\n",
    "print(f\"tech_stack  : {tech_stack}\")\n",
    "tech_stack.add(\"CSS\")\n",
    "tech_stack.discard(\"HTML\")\n",
    "\n",
    "reporter_tech = reporters.union(tech_stack)\n",
    "print(f\"union       : {reporter_tech}\")\n",
    "print(f\"intersection: {reporters.intersection(tech_stack)}   difference : {reporters.difference(tech_stack)}\")\n",
    "print(f\"Critical present  : {'Yes' if (any(issue['priority'] == 'Critical' for issue in issues)) else 'No'} - flag for immediate review.\")\n",
    "\n",
    "print(\"-\" * 50)\n",
    "priority_count = {}\n",
    "for issue in issues:\n",
    "    p = issue['priority']\n",
    "    if p not in priority_count:\n",
    "        priority_count[p] = 1\n",
    "    else:\n",
    "        priority_count[p] += 1\n",
    "\n",
    "print(f\"priority keys : {priority_count.keys()}\")\n",
    "print(f\"priority values : {priority_count.values()}\")\n",
    "\n",
    "\n",
    "status_open = []\n",
    "status_in_progress = []\n",
    "status_resolved = []\n",
    "for issue in issues:\n",
    "    if issue['status'] == \"Open\":\n",
    "        status_open.append(issue['title'])\n",
    "    elif issue['status'] == \"In Progress\":\n",
    "        status_in_progress.append(issue['title'])\n",
    "    else:\n",
    "        status_resolved.append(issue['title'])\n",
    "        \n",
    "status_groups = {}\n",
    "if len(status_open)!=0:\n",
    "    status_groups['Open'] = status_open\n",
    "if len(status_in_progress)!=0:\n",
    "    status_groups['In Progress'] = status_in_progress\n",
    "if len(status_resolved)!=0:\n",
    "    status_groups['Resolved'] = status_resolved\n",
    "print(f\"Status_Groups -> {'   |   '.join(f'{k} : {v}' for k, v in status_groups.items())}\")\n",
    "print(f\"Status Keys : {status_groups.keys()}\")\n",
    "print(f\"Status Values : {status_groups.values()}\")\n",
    "\n",
    "top_count = 0\n",
    "for reporter in reporters:\n",
    "    cnt = 0\n",
    "    for issue in issues:\n",
    "        if issue['reporter'] == reporter:\n",
    "            cnt += 1\n",
    "    if cnt > top_count: \n",
    "        top_count = cnt\n",
    "        top_reporter = reporter\n",
    "print(f\"Top reporter   : {top_reporter} ({top_count} issues)\")\n",
    "\n",
    "issues[0].pop(\"type\")\n",
    "print(f\"After pop('type') : {issues[0]}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6297233d",
   "metadata": {},
   "source": [
    "## Section3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "13c066d6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Folder 'space_recommendation'  already exists\n",
      "space_recommendation/project_report.txt\n",
      "{'Critical': 2, 'High': 1, 'Medium': 1, 'Low': 1}\n",
      "Files saved : ['project_report.txt', 'issues.csv']\n",
      "\n",
      "\n",
      "----------------------------------------\n",
      "File: project_report.txt\n",
      "---------------- read() ---------------- \n",
      "==================================================\n",
      "Space - Recommendation - Open Source Project\n",
      "Project Lead : Yerim\n",
      "==================================================\n",
      "\n",
      "======= Project Info =======\n",
      "Project : Space Recommendation   Version : 1.0   Lead : Yerim\n",
      "\n",
      "======= Contributors =======\n",
      "Contributors : 4   Names : ['Yerim', 'James', 'Bob', 'Chloe']\n",
      "{'name': 'Yerim', 'role': 'Junior Developer', 'language': 'Python', 'commits': 10, 'country': 'Republic of Korea', 'status': 'Active'}\n",
      "{'name': 'James', 'role': 'Senior Developer', 'language': 'Java', 'commits': 200, 'country': 'China', 'status': 'Active'}\n",
      "{'name': 'Bob', 'role': 'Instructor', 'language': 'C', 'commits': 5000, 'country': 'United States', 'status': 'Active'}\n",
      "{'name': 'Chloe', 'role': 'Frontend Developer', 'language': 'CSS', 'commits': 222, 'country': 'Japan', 'status': 'Active'}\n",
      "\n",
      "======= Issues =======\n",
      "Issues : 5  Open: 2  Reporters : 4\n",
      "{'id': 1, 'title': '404 Error', 'priority': 'Critical', 'reporter': 'James', 'status': 'Open'}\n",
      "{'id': 2, 'title': '500 Error', 'type': 'Bug', 'priority': 'High', 'reporter': 'Yerim', 'status': 'In Progress'}\n",
      "{'id': 3, 'title': 'New code submitted', 'type': 'Feature', 'priority': 'Medium', 'reporter': 'Bob', 'status': 'Open'}\n",
      "{'id': 4, 'title': '200 Success', 'type': 'Feature', 'priority': 'Low', 'reporter': 'Chloe', 'status': 'Resolved'}\n",
      "{'id': 5, 'title': 'Syntax Error', 'type': 'Bug', 'priority': 'Critical', 'reporter': 'James', 'status': 'In Progress'}\n",
      "\n",
      "======= Analysis =======\n",
      "Tech Stack : {'Python', 'CSS', 'C', 'Java'}\n",
      "Critical: 2  High: 1  Medium: 1  Low: 1\n",
      "\n",
      "======= Reporters =======\n",
      "Reporters : {'James', 'Yerim', 'Chloe', 'Bob'}\n",
      "Top Reporter : James (2 issues)\n",
      "\n",
      "-------------- readline() --------------\n",
      "Line 1 : ==================================================\n",
      "\n",
      "Line 2 : Space - Recommendation - Open Source Project\n",
      "\n",
      "-------------- readlines() --------------\n",
      "Total lines : 30   Critical/High lines : 4\n",
      "Critical/High lines : [\"{'id': 1, 'title': '404 Error', 'priority': 'Critical', 'reporter': 'James', 'status': 'Open'}\\n\", \"{'id': 2, 'title': '500 Error', 'type': 'Bug', 'priority': 'High', 'reporter': 'Yerim', 'status': 'In Progress'}\\n\", \"{'id': 5, 'title': 'Syntax Error', 'type': 'Bug', 'priority': 'Critical', 'reporter': 'James', 'status': 'In Progress'}\\n\", 'Critical: 2  High: 1  Medium: 1  Low: 1\\n']\n",
      "\n",
      "\n",
      "----------------------------------------\n",
      "File: issues.csv\n",
      "---------------- read() ---------------- \n",
      "id, title, priority, reporter, status\n",
      "1, 404 Error, Critical, James, Open\n",
      "2, 500 Error, Bug, High, Yerim, In Progress\n",
      "3, New code submitted, Feature, Medium, Bob, Open\n",
      "4, 200 Success, Feature, Low, Chloe, Resolved\n",
      "5, Syntax Error, Bug, Critical, James, In Progress\n",
      "\n",
      "-------------- readline() --------------\n",
      "Line 1 : id, title, priority, reporter, status\n",
      "\n",
      "Line 2 : 1, 404 Error, Critical, James, Open\n",
      "\n",
      "-------------- readlines() --------------\n",
      "Total lines : 6   Critical/High lines : 3\n",
      "Critical/High lines : ['1, 404 Error, Critical, James, Open\\n', '2, 500 Error, Bug, High, Yerim, In Progress\\n', '5, Syntax Error, Bug, Critical, James, In Progress\\n']\n",
      "==================================================\n",
      "             Space Recommendation\n",
      "==================================================\n",
      "Project : Space Recommendation     Version : 1.0     Lead : Yerim\n",
      "Contributors : 4     Names : ['Bob', 'Chloe', 'James', 'Yerim']\n",
      "Issues : 5     Open : 2     Reporters : 4\n",
      "Tech Stack : {'Python', 'CSS', 'C', 'Java'}\n",
      "Reporters : {'James', 'Yerim', 'Chloe', 'Bob'}\n",
      "Top Reporters : James (2 issues)\n",
      "Critical: 2   High: 1   Medium: 1   Low: 1\n",
      "Report : space_recommendation/project_report.txt\n",
      "CSV : space_recommendation/issues.csv\n",
      "==================================================\n",
      "Space Recommendation complete. Thank you for contributing to open source!\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "#print(f\"Current directory: {os.getcwd()}\")\n",
    "\n",
    "## create folder_name\n",
    "folder_name = project[0].lower().replace(\" \", \"_\")\n",
    "\n",
    "## create folder\n",
    "if not os.path.exists(folder_name):\n",
    "    os.mkdir(folder_name)\n",
    "    print(f\"Folder created: {folder_name}/\")\n",
    "else:\n",
    "    print(f\"Folder '{folder_name}'  already exists\")\n",
    "\n",
    "## create file path\n",
    "report_path = os.path.join(folder_name, 'project_report.txt')\n",
    "issues_path = os.path.join(folder_name, 'issues.csv')\n",
    "print(report_path)\n",
    "print(priority_count)\n",
    "\n",
    "## create file with wraping try/except IOError\n",
    "try:\n",
    "    with open(report_path, \"w\") as f:\n",
    "        f.write(\"=\" * 50 + \"\\n\")\n",
    "        f.write(\"Space - Recommendation - Open Source Project\\n\")\n",
    "        f.write(\"Project Lead : Yerim\\n\")\n",
    "        f.write(\"=\" * 50 + \"\\n\")\n",
    "\n",
    "        f.write(\"\\n======= Project Info =======\\n\")   \n",
    "        f.write(f\"Project : {project[0]}   Version : {project[1]}   Lead : {project[4]}\\n\")\n",
    "\n",
    "        f.write(\"\\n======= Contributors =======\\n\")\n",
    "        f.write(f\"Contributors : {len(contributors)}   Names : {[d['name'] for d in contributors]}\\n\")\n",
    "        for c in contributors:\n",
    "            f.write(f\"{c}\\n\")\n",
    "\n",
    "        f.write(\"\\n======= Issues =======\\n\")\n",
    "        f.write(f\"Issues : {len(issues)}  Open: {sum(1 for issue in issues if issue['status']=='Open')}  Reporters : {len(reporters)}\\n\")\n",
    "        for issue in issues:\n",
    "            f.write(f\"{issue}\\n\")\n",
    "\n",
    "        f.write(\"\\n======= Analysis =======\\n\")\n",
    "        f.write(f\"Tech Stack : {tech_stack}\\n\")\n",
    "        f.write(f\"{'  '.join(f'{k}: {v}' for k, v in priority_count.items())}\\n\")\n",
    "\n",
    "        f.write(\"\\n======= Reporters =======\\n\")\n",
    "        f.write(f\"Reporters : {reporters}\\n\")\n",
    "        f.write(f\"Top Reporter : {top_reporter} ({top_count} issues)\\n\")\n",
    "\n",
    "except IOError:\n",
    "    print(\"Error in 'project_report.txt'\")\n",
    "\n",
    "try:\n",
    "    with open(issues_path, \"w\") as f: \n",
    "        f.write(\"id, title, priority, reporter, status\\n\")\n",
    "        for issue in issues:\n",
    "            f.write(f\"{', '.join(f'{v}' for v in issue.values())}\\n\")\n",
    "except IOError:\n",
    "    print(\"Error in 'issues.csv'\")\n",
    "\n",
    "\n",
    "print(f\"Files saved : {os.listdir(folder_name)}\")\n",
    "\n",
    "\n",
    "## read file with wraping try/except FileNotFoundError\n",
    "for file in os.listdir(folder_name):\n",
    "    file_path = os.path.join(folder_name, file)\n",
    "    try:\n",
    "        with open(file_path, \"r\") as f:\n",
    "            print(\"\\n\\n\" + \"-\" * 40)\n",
    "            print(\"File:\", file)\n",
    "\n",
    "            print(\"---------------- read() ---------------- \")\n",
    "            print(f.read())\n",
    "\n",
    "        with open(file_path, \"r\") as f:\n",
    "            print(\"-------------- readline() --------------\")\n",
    "            print(f\"Line 1 : {f.readline()}\")\n",
    "            print(f\"Line 2 : {f.readline()}\")\n",
    "\n",
    "        with open(file_path, \"r\") as f:\n",
    "            print(\"-------------- readlines() --------------\")\n",
    "            lines = f.readlines()\n",
    "            print(f\"Total lines : {len(lines)}   Critical/High lines : {len([l for l in lines if 'Critical' in l or 'High' in l])}\")\n",
    "            print(f\"Critical/High lines : {[l for l in lines if 'Critical' in l or 'High' in l]}\")\n",
    "    except FileNotFoundError:\n",
    "        print(f\"File '{file}' Not Found\")\n",
    "\n",
    "\n",
    "\n",
    "## Final\n",
    "print(\"=\"  * 50)\n",
    "print(f\"             {project[0]}\")\n",
    "print(\"=\"  * 50)\n",
    "print(f\"Project : {project[0]}     Version : {project[1]}     Lead : {project[4]}\")\n",
    "print(f\"Contributors : {len(contributors)}     Names : {names}\")\n",
    "print(f\"Issues : {len(issues)}     Open : {sum(1 for d in issues if d['status'] == 'Open')}     Reporters : {len(reporters)}\")\n",
    "print(f\"Tech Stack : {tech_stack}\")\n",
    "print(f\"Reporters : {reporters}\")\n",
    "print(f\"Top Reporters : {top_reporter} ({top_count} issues)\")\n",
    "print(f\"{'   '.join(f'{k}: {v}' for k, v in priority_count.items())}\")\n",
    "print(f\"Report : {report_path}\")\n",
    "print(f\"CSV : {issues_path}\")\n",
    "print(\"=\"  * 50)\n",
    "print(f\"{project[0]} complete. Thank you for contributing to open source!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9fbaa890",
   "metadata": {},
   "source": [
    "## ★"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "d9de8150",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Urgent issues: ['404 Error', '500 Error', 'Syntax Error']\n",
      "Count of urgent titles: 3\n",
      "Top Reporter : James (2 issues)\n",
      "\n",
      "======= Urgent Issues =======\n",
      "404 Error\n",
      "500 Error\n",
      "Syntax Error\n",
      "\n"
     ]
    }
   ],
   "source": [
    "## Part 1\n",
    "urgent = [issue['title'] for issue in issues if issue['priority']=='Critical' or issue['priority']=='High']\n",
    "print(f\"Urgent issues: {urgent}\")\n",
    "print(f\"Count of urgent titles: {len(urgent)}\")\n",
    "\n",
    "\n",
    "## Part 2\n",
    "with open(report_path, 'a') as f:\n",
    "    f.write(\"\\n======= Urgent Issues =======\\n\")\n",
    "    for i in urgent:\n",
    "        f.write(f\"{i}\\n\")\n",
    "\n",
    "with open(report_path, 'r') as f:\n",
    "    lines = f.readlines()\n",
    "    print(''.join(lines[-6:]))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "explain",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
